### ISSUE TITLE
How to prepare assets for the app center

### ISSUE THREAD

**Issue by luisivan** [aragon/hack#100]
In order to showcase Aragon apps on the upcoming app center, we need to explain how to prepare:
- Small icon
- Bigger icon
- Description
- Screenshots

That should be documented and added to the dev portal.

**Comment by luisivan** [comment]
Design is ready https://www.figma.com/file/XOINhAadQHKCYghNlistQZGc/App-store-asset-guidelines?node-id=0%3A1

**Comment by sohkai** [comment]
Completed with https://github.com/aragon/hack/pull/125.
