### ISSUE TITLE
List dependencies and instructions for installing them

### ISSUE THREAD

**Issue by john-light** [aragon/hack#104]
I notice on the [CLI page](https://hack.aragon.org/docs/cli-usage.html) for example, the npm and git commands are entered, which assumes that the user has these installed already. It would be worth noting at the beginning of the documentation what dependencies are required to go through the documentation (including the minimum version required) and how to install the dependency.

**Comment by sohkai** [comment]
Perhaps related to #77, and maybe we could generalize it to be a starting help page for all OSes?

**Comment by john-light** [comment]
That'd be good too, since the instructions may vary for different OSes.

**Comment by 0xGabi** [comment]
Maybe for `git` we can mention you'll need it in [environment setup](https://hack.aragon.org/docs/getting-started#environment-setup) and then link this section in the aragonCLI introduction

**Comment by sohkai** [comment]
More installation prerequisites were added to https://hack.aragon.org/docs/cli-intro#installation-pre-requisites.
