### ISSUE TITLE
change kits -> templates

### ISSUE THREAD

**Issue by john-light** [aragon/hack#111]
e.g. https://hack.aragon.org/docs/kits-intro

See: https://forum.aragon.org/t/on-aragon-naming/203

**Comment by sohkai** [comment]
We should provide a smooth transition into the "Templates" terminology.

Perhaps we can rename the kits to templates but leave notes on their pages saying that these used to be called kits (and in some places they may still be called kits)?

We will also need to provide the rename in aragonCLI: https://github.com/aragon/aragon-cli/issues/404

cc @0x6431346e @0xGabi
