### ISSUE TITLE
Check the publish guide

### ISSUE THREAD

**Issue by kernelwhisperer** [aragon/hack#128]
It seems a bit broken, i.e.:

`npm run publish:major --environment staging`

translates to `aragon apm publish major "staging"`
not ` aragon apm publish major "--environment" "staging"`

it's missing `--`

**Comment by sohkai** [comment]
@0xGabi @0x6431346e Has this been completed?

**Comment by 0xGabi** [comment]
I don't think so! Will take a look 👍
