### ISSUE TITLE
Line breaks inbetween functions in reference docs

### ISSUE THREAD

**Issue by Quazia** [aragon/hack#14]
I think line breaks between elements for the reference docs would be really helpful. I keep reading on past the return.

**Comment by luisivan** [comment]
I agree

**Comment by cjyabraham** [comment]
So just to clarify, are you saying on a page like [this](http://localhost:3000/docs/cli-usage.html) you want the commands separate from one another more clearly?  I will try and use a different style for the command names rather than the code block style.

**Comment by Quazia** [comment]
https://hack.aragon.org/docs/aragonjs-ref.html#accounts
It's not a matter of text styling, I think it needs an actual line break or a visual element beyond text styling in between the separate functions.

**Comment by cjyabraham** [comment]
Ok, [this is done](https://github.com/aragon/hack/pull/51).  I standardized all three of our reference docs to follow the same style.

**Comment by cjyabraham** [comment]
@Quazia, the PR has been merged.  I'll let you close out this issue if you think it's been satisfactorily resolved.
