### ISSUE TITLE
Culture link on Aragon.org job offers seems broken

### ISSUE THREAD

**Issue by ottodevs** [aragon/hack#140]
I dunno if it is actually an issue seems it is present on archive pages, but I just tried to use the search box to look for that culture page and just found these broken links:
https://wiki.aragon.org/archive/jobs/exec-assistant/
(seems to be happening on every job offer page like this)

**Comment by sohkai** [comment]
cc @Smokyish, is there a way for us to remove archived links from being indexed in the wiki's search?

**Comment by sohkai** [comment]
Not related to the documentation site, and the wiki has been restructured with various pages being in archive (for example, the mentioned page is now available again in the wiki).
