### ISSUE TITLE
Docusaurus? 🦕

### ISSUE THREAD

**Issue by yeqbfgxjiq** [aragon/hack#141]
Hey! I'm creating [a website and docs for the Coop DAO](https://aragoncoop.github.io/coop-dao-docs/). Part of that involves creating documentation around the Aragon apps used to build the DAO so that people know how it works, why it works, and how they can build similar things. 

I don't want to reinvent the wheel or do unnecessary work so I'm trying to learn about and link to all dev tools and tutorials in the Aragon ecosystem. Browsing through hack.aragon, the website UI and repo file structure is remarkably similar to the Coop DAO Docs... Did you guys use [Docusaurus](https://docusaurus.io)? I did! lol. This isn't an actual issue or anything I'm just curious.

Also, do you guys have plans to build tutorials and education resources around [Auturk's new TPS apps](https://tps.autark.xyz/#/)? If so, that would be great to know so that we don't duplicate our efforts :)

**Comment by 0xGabi** [comment]
Hey @burrrata, yes we use a modified version of [Docusaurus](https://github.com/aragon/Docusaurus).

There is no plan to build education around TPS yet that I'm aware. Is going to be a must on the near term future. I'm not sure the place where to put Aragon apps related documentation, maybe we should have a special section or even a hole new page. 

 As TPS are several apps in one you might need some help, I'll ping @hackingclimate he is really exited to help with documentation

**Comment by endiliey** [comment]
Hi, @docusaurus maintainer here.

I see what you did here. Great job 😉 

I love what you are doing. <3

**Comment by unixpi** [comment]
Thanks for pinging me @0xGabi!  @burrrata I'd be more than happy to work with you on tutorials and resources around TPS :)

Let me know if/when you decide to go ahead with them.

**Comment by sohkai** [comment]
@burrrata Most of the user-land documentation for the "core" apps (aragon-apps) is provided in the form of a user guide: https://wiki.aragon.org/tutorials/Aragon_User_Guide/.

We could think about how to scale this into potentially its own site where other applications could be listed, if we wanted to unify the documentation that way. Otherwise, I'd expect each flock team to provide some measure of documentation for their own applications, similar to a typical app store where the onus is on the developers.

**Comment by yeqbfgxjiq** [comment]
@hackingclimate Awesome :) I think the most interesting thing would be to document the apps in the context of an actual DAO. Then in addition to explaining what the apps are and what they do, you can provide an example people can interact with. Then there's context that makes various design decisions or functionalities come to life. Not sure if the best way to do that would be an existing DAO that people use or a demo DAO/Template? Maybe it would be worth creating a DAO specifically to be used along-side the docs? I dunno, what do you think?

**Comment by unixpi** [comment]
@burrrata I think documenting the apps in the context of an DAO is a great idea. I'm also not sure what the best approach is.. will have a think. When do you want to get started on this?

**Comment by yeqbfgxjiq** [comment]
@hackingclimate It looks like we're launching a [DAO](https://rinkeby.aragon.org/#/0xe520428C232F6Da6f694b121181f907931fD2211) called [1Hive](https://1hive.github.io/mvp/) that uses TPS apps. Part of the [MVP](https://github.com/1Hive/mvp) is going to be creating [user guides](https://1hive.github.io/mvp/docs/guides/welcome.html) so that people can actually use the DAO comfortably and engage with the community. These docs will explain the TPS apps that are used in 1Hive, why they were chosen, and how they work. Currently we're using the the Dot Voting, Projects, and Allocations apps from [TPS](https://github.com/AutarkLabs/planning-suite) so we'll start there, but there's plans to upgrade to a V2 model in the next few months. [Just opened an Issue to work on that](https://github.com/1Hive/mvp/issues/11) and if you wanted to help us that would be awesome! 🐝 

Edit: just [updated the docs](https://1hive.github.io/mvp/docs/welcome) so that there's a skeleton with some starter content. It needs more/better content, but hopefully this makes it easier to get started and fill it with useful info :)

**Comment by 0xGabi** [comment]
>Not sure if the best way to do that would be an existing DAO that people use or a demo DAO/Template?
 
I like this idea, we may guide people to use `create-aragon-app` and give them a new `Template` file which deploy a DAO with all the apps we decide to include (similar to [this](https://github.com/aragon/aragon-react-boilerplate/blob/master/contracts/Template.sol) or [this](https://github.com/AutarkLabs/planning-suite/blob/dev/kits/planning-suite/contracts/PlanningSuite.sol))

**Comment by yeqbfgxjiq** [comment]
Yeah that would be great! Maybe we could add DAO demo templates that to the [Ideas repo](https://github.com/1Hive/ideas) for V2, and then on V1 just do general explanations with text and pictures?

**Comment by yeqbfgxjiq** [comment]
@0xGabi @hackingclimate 
Just [updated the 1HIve docs](https://1hive.github.io/mvp/docs/welcome) for the TPS apps used (allocations, dot-voting, projects). Turns out Autark already created a [demo DAO with TPS enabled](https://rinkeby.aragon.org/#/dune.aragonid.eth). Also anyone who wants can [set up a new TPS enabled DAO on Rinkeby](https://rinkeby.autark.xyz/) to explore the process themselves. Furthermore, Autark has [integration guides](https://github.com/AutarkLabs/planning-suite/blob/master/docs/GETTING_STARTED.md) for adding TPS to currently existing DAOs. There's also [this walk through](https://medium.com/@stellarmagnet/that-planning-suite-live-on-rinkeby-c2332e2e5e27) and [brief descriptions with screenshots](https://www.autark.xyz/aragon-apps) on the website. All that being said, TPS apps are still in testing and have not been deployed to mainnet yet and new bugs/changes are still possible.

For the purposes of 1Hive, linking to the current resources/info makes the most sense because then as things change or the apps get upgraded we can just change a few links rather than having the overhead of writing all new docs. If, however, you guys have any other ideas on how to make the material more interesting/engaging I'm all for it :)

**Comment by yeqbfgxjiq** [comment]
Started a project to make Hack.Aragon style developer hubs and documentation easy to build and maintain for every Aragon project.
- https://github.com/burrrata/hack.aragon4all

To test out the idea I'm creating a demo dev-hub with docs for Autark's TPS. It's currently a WIP with placeholder content, but you can watch it iteratively being built here.
- https://www.burrrata.ch/hack.aragon4all/

To refine the model I'm reaching out to everyone I can in the Aragon ecosystem to understand their desires and pain points around documentation and dev ux. This includes devs who build Aragon apps, but also devs who want to learn about and use Aragon apps. If anyone wants provide feedback on those things, or knows anyone who would that would be awesome! The best way to reach me is [@burrrata on Keybase](https://keybase.io/burrrata) :) 

<br>

Anyways, thought that might be interesting to you guys, but also, it's probably safe to close this Issue as I've answered/solved my own problem lol.
