### ISSUE TITLE
Sanity check Your First Aragon App

### ISSUE THREAD

**Issue by sohkai** [aragon/hack#15]
There's a few things that are confusing, e.g. are we using the bare or react boilerplate? Or are we getting them to make the contracts themselves?

**Comment by cjyabraham** [comment]
I agree with the confusion.  We are going to be overhauling the tutorial and creating more so will clear that up then.

**Comment by cjyabraham** [comment]
I'm closing #69 since this issue is very similar.  So you can create a new boilerplate for the tutorial or don't use one at all... whatever makes the most sense for the tutorial.
