### ISSUE TITLE
Iterate on How to use Frame guide

### ISSUE THREAD

**Issue by 0xGabi** [aragon/hack#150]
This issue was funded with **90 DAI**, see more issues on our dao [projects app](https://rinkeby.aragon.org/#/meshteam.aragonid.eth/0x2b2290c2370cbc59e7c77bd36072f801d5e996c8).
---
TODO:

- [ ] depositing both ETH and tokens through an organization's Finance app from the client

- [ ] voting from the client

**Comment by sohkai** [comment]
Closing; these types of user-docs now live in help.aragon.org.
