### ISSUE TITLE
GitHub guide for contributors

### ISSUE THREAD

**Issue by 0xGabi** [aragon/hack#160]
How to contribute with documentation.

---
This issue is funded with **150 DAI**, see more issues on our dao [projects app](https://rinkeby.aragon.org/#/meshteam.aragonid.eth/0x2b2290c2370cbc59e7c77bd36072f801d5e996c8).

**Funded**: [Mainnet Tx](https://etherscan.io/tx/0xcc9ec2062b8a17400144908bd99211de3f25bfe03c4bc3371697b52403834b6b)

**Comment by 0xGabi** [comment]
@hackingclimate Thank you for you work with this guide and also renew the getting started page. Can you provide me with a mainnet address?

**Comment by unixpi** [comment]
@0xGabi why of course! My mainnet address is 0x2A1Aa961ae9B69D587dF390e2Be7e700E35822aA
