### ISSUE TITLE
Guide: Bounties and Autark's project app

### ISSUE THREAD

**Issue by unixpi** [aragon/hack#163]
This issue was funded with **90 DAI**, see more issues on our dao [projects app](https://rinkeby.aragon.org/#/meshteam.aragonid.eth/0x2b2290c2370cbc59e7c77bd36072f801d5e996c8).
---
Create a guide on how to use Autark's projects app to work on issues.

Things to cover:

1. How to request to work on an issue
2. How to claim a bounty
3. How to fund an issue

See https://github.com/aragon/hack/pull/154#issuecomment-494591016 and https://github.com/aragon/hack/issues/160 for an outline of the process (modulo 3).

**Comment by sohkai** [comment]
Closing; these types of guides should either live in help.aragon.org or OpenEnterprise's own documentation.
