### ISSUE TITLE
Who wrote the docs sync scripts?

### ISSUE THREAD

**Issue by yeqbfgxjiq** [aragon/hack#170]
Have a bunch of ideas I want to contribute to [Docusaurus2](https://v2.docusaurus.io/), one of them being a sync feature to pull docs from other repos and display them in the Docusaurus docs. While I've recreated and refined that idea for my own usecases, it originally came from you guys. If I end up contributing that feature to Docusaurus2, what would be the best way to give credit where credit is due? Thanks :)

**Comment by luisivan** [comment]
Pretty sure it was @bingen!

**Comment by 0xGabi** [comment]
I think it was @0x6431346e on https://github.com/aragon/hack/commit/942b460a04ea959626b152571c1fa6a155551405

**Comment by luisivan** [comment]
Ouh, thanks for the heads up then haha

**Comment by 0xGabi** [comment]
I'll close this issue now that the mystery was solved 😁
