### ISSUE TITLE
Add CONTRIBUTING file

### ISSUE THREAD

**Issue by john-light** [aragon/hack#19]
Create a CONTRIBUTING.md file and contributor guidelines for this repo.

**Comment by cjyabraham** [comment]
To confirm, you're talking about guidelines for contributing to the hack.aragon docs right?  I have started a list at the bottom of [my doc here](https://docs.google.com/document/d/1B1nyb95LgBtrWY8Av0FnvnpUfvOb13wfjGZb28svSVs/edit#).  Could you give me an example of a CONTRIBUTING.md file, what it should look like and where it might live?

**Comment by john-light** [comment]
@cjyabraham great question thanks. Yes exactly. You'll notice an issue like this on most repos in this org that do not yet have these guidelines. See examples of contributing guidelines here:

https://blog.github.com/2012-09-17-contributing-guidelines/

**Comment by cjyabraham** [comment]
[Here's a first draft.](https://github.com/aragon/hack/pull/50)

**Comment by john-light** [comment]
@cjyabraham thanks! I suggest adding at least one other reviewer who contributes to / uses the docs to take a look. with that I'll get out of your way here :)
