### ISSUE TITLE
This is for you, developer.

### ISSUE THREAD

**Issue by yeqbfgxjiq** [aragon/hack#190]
Opening up hack.aragon I was greeted with a new homepage. It looks beautiful, but then I scrolled down and the "This is for you, developer." section is really weird. Maybe just remove that part?

**Comment by burrrata** [comment]
Just refreshed the page and it looks like everything is huge and doesn't fit the screen. Maybe you guys are just testing stuff out then. I dunno. If that's the case then feel free to just ignore this lol

**Comment by sohkai** [comment]
Thanks for the feedback. However, "really weird" is not very descriptive or helpful.

Could the prose be improved? Is it the visuals? Or is it something else?

**Comment by yeqbfgxjiq** [comment]
Good point! Hope this is more helpful:
- The background of the section is kind of a brownish color (at least on my screen) and it feels like it clashes with the blues and greys of the overall Aragon website/theme.
- The phrasing of "This is for, developer" is unintuitive. 
    - First, addressing someone as "developer" sounds like soviets calling someone "comrade." I don't think that's the intention, but that's the vibe it gives off.
    - Second, what if I'm not a "developer" (or don't self identify as one), but want to learn about the Aragon stack? This feels a bit alienating. 
- Instead of the current tagline, here's a few (not very good) alternative suggestions:
    - "Empowering free organization"
    - "The frontier of human coordination at scale"
    - "This is for you" (this is my favorite of these suggestions - just drop the developer portion)
- The image is fine. It's a little different than the logos and cool graphics throughout most of the Aragon website, but people are cool too. It was mainly the tagline that could use improvement.

Hope that's more helpful and sorry for the vague Issue! :)

**Comment by sohkai** [comment]
Understood, and thanks for clarifying.

We'll be able to revisit these concerns with the rebranding effort (#187). As it is, this portal is intended to be for developers, and you need to have some technical knowledge to understand most of the documents.
