### ISSUE TITLE
Add technical specs (e.g. json files)

### ISSUE THREAD

**Issue by sohkai** [aragon/hack#23]
Document the specs in https://github.com/aragon/specs as well as the schemas and definitions of the `arapp.json`

**Comment by cjyabraham** [comment]
When I go to https://github.com/aragon/specs I get a 404.  Has this moved?

**Comment by sohkai** [comment]
@cjyabraham Those are still in a private repo... @izqui do you think we should just make it public and archive it?

**Comment by sohkai** [comment]
@cjyabraham I have now made https://github.com/aragon/specs public.

**Comment by cjyabraham** [comment]
So, to see if I understand, we want to copy these specs to hack.aragon.org?  Would you see these going in a separate Specs section or in the aragon.js section?

**Comment by cjyabraham** [comment]
@sohkai, I'm still a bit confused as to where these should reside and how they should be introduced.  Would you or one of the other devs have a bit of time to take a first pass at this?

**Comment by sohkai** [comment]
@cjyabrahamI was thinking of adding it to the aragonAPI section. I'll try to provide some structure of how I see this being added now that we're done the renaming :).

**Comment by 0xGabi** [comment]
@sohkai Are the specs documents still relevant. How we add more information to existing aragonAPI?

**Comment by sohkai** [comment]
@0xGabi I'd call them still relevant information we should move to the aragonAPI section. I'd propose adding a new page with them to describe both the architecture of Aragon apps and their communication channels.
