### ISSUE TITLE
Highlight potentially insecure contract functions

### ISSUE THREAD

**Issue by sohkai** [aragon/hack#24]
As pointed out in both the WHG and CD audits, we should make sure to document and **highlight** the contract functions that are insecure or incredibly powerful.

Examples:

- `Kernel.setApp()`
- `EVMScriptRunner.runScript()`
- ACL permission functions

**Comment by cjyabraham** [comment]
My senses is that this can be closed now due to your recent edits @sohkai.  Feel free to reopen if you disagree.

**Comment by sohkai** [comment]
I think we may want to add even more warnings in the future, and perhaps even provide a "safety" guide, but that can be a separate concern in the future.
