### ISSUE TITLE
Expand publishing guide so that users can easily deploy to open.aragonpm.eth

### ISSUE THREAD

**Issue by sohkai** [aragon/hack#33]

**Comment by cjyabraham** [comment]
So are you suggesting we need a few more steps [here](https://hack.aragon.org/docs/apm.html) to show interactions with open.aragonpm.eth?  Or would it be better to have a section in a tutorial that walks through how to do this?

**Comment by sohkai** [comment]
I think another page in the "Aragon Package Manager" to show interactions with it (using the CLI to fetch information, publish information, how to select which APM instance to use, etc) would be ideal.

**Comment by cjyabraham** [comment]
We do have some APM commands listed [here](https://hack.aragon.org/docs/cli-usage.html#apm-commands).  It sounds like there are a few more to add?  If you could provide me with the info I could update the doc.

I could then create a link from [here](https://hack.aragon.org/docs/apm.html#interacting-with-apm-apmjs-and-aragon-cli) to that section of the CLI doc just to tie them together.  What do you think?

**Comment by sohkai** [comment]
I think that page is pretty up to date with the commands offered by the CLI.

With the new `environments` object in the `arapp.json`, I think the most important bit for new users would be to guide them to the [explanation](https://hack.aragon.org/docs/cli-usage.html#the-arappjson-file) and an example (e.g. setting up the example so it publishes to `open.aragonpm.eth`).

Maybe we could have a tips-and-tricks page in the CLI docs for things you might want to do, like changing the `arapp.json` so you can publish to `open.aragonpm.eth`?

cc @izqui @Quazia

**Comment by 0xGabi** [comment]
Close in #99
