### ISSUE TITLE
Glossary for developer terminology

### ISSUE THREAD

**Issue by 0x-r4bbit** [aragon/hack#38]
As someone who's starting out getting to know the aragon ecosystem, I often ran into cases where some terminology used throughout the project threw me off as they had a different meaning than what I've expected. 

This can be simple cases like

> What is an APM Repository?

Is it a Git repository? Is it just an implementation of a different kind of repository?

Or

> What is a package in APM? What does package even mean in this context?

As many people here know, APM takes care of a lot of things (distributing content via IPFS, deploying app contracts, managing versions via APM Repositories and so on.

I think it'd be good to introduce a glossary in the developer portal that gives short and concise explanations of the terminology that's being used, especially for the ambiguous ones.

If the team and community agrees that this is something that should be added, we could start collecting all the terms here that should be covered by the glossary.

Here are a few:

- [x] Aragon CLI
- [x] APM (Aragon Package Manager)
- [x] APM Repository
- [x] Aragon Apps / Sandboxed Apps
- [x] Aragon UI
- [x] Wrapper (I wish there was a less general term for this thing 😅)
- [x] Aragon DAC
- [x] aragon.js 
- [x] aragonOS
- [x] DAO Kits
- [x] Aragen
- [x] aragon-id
- [x] DAO (sure, Decentralized Autonomous Organisation, but in the context of Aragon it could also mean the organisation represented in the app, or the app itself even?)

And there's prolly a lot more (feel free to add them here). Again, as someone who's new to this universe will be very overwhelmed by all the different components and how they fit in the big picture. 

I also hope that, before a 1.0 there's opportunity to maybe even rename some things and streamline the terminology as much as possible.

**Comment by luisivan** [comment]
I wholeheartedly agree with this

**Comment by luisivan** [comment]
So now there is a glossary at https://wiki.aragon.org/documentation/glossary/, which contains mostly user-facing names but also dev ones. I'd say moving all dev names to https://hack.aragon.org/docs/getting-started.html, and adding the remaining ones there, would be a good start

**Comment by luisivan** [comment]
Moved all the dev glossary to https://hack.aragon.org/docs/glossary.html. I think this is a good starting point, so closing the issue. Also thanks a lot @PascalPrecht for pointing out the importance of having this!
