### ISSUE TITLE
Document usage of --environment option in CLI guide

### ISSUE THREAD

**Issue by izqui** [aragon/hack#53]
https://github.com/aragon/aragon-cli/pull/230

**Comment by izqui** [comment]
@perissology can you take on this?

**Comment by cjyabraham** [comment]
I think this can be closed as he has [already done it](https://github.com/aragon/hack/commit/a54a23fcea094f2366d325ad1c6b9bd557f50ab1#diff-d6755dcc5432538a36f66f5422c10077).

**Comment by sohkai** [comment]
@cjyabraham Looks like we forgot to document when the `--environment` option can be used; I've changed the issue title to reflect this.

**Comment by cjyabraham** [comment]
@perissology can do this but I can't currently "assign" him to the issue for some reason.

**Comment by 0xGabi** [comment]
Include how to add a custom provider

**Comment by 0xGabi** [comment]
Close in #99
