### ISSUE TITLE
improve diagrams on hack.aragon

### ISSUE THREAD

**Issue by cjyabraham** [aragon/hack#57]
Most of the diagrams used on hack.aragon could be improved by doing the following:
- increasing the font size; in a lot diagrams some of the text is hardly legible
- use some color

@izqui made this diagrams originally and may have the source files.

**Comment by cjyabraham** [comment]
One idea from @0x6431346e is to use [Mermaid](https://mermaidjs.github.io/)

**Comment by cjyabraham** [comment]
Diagrams that need updating:
2 on [this page](https://hack.aragon.org/docs/apm.html)
3 on [this page](https://hack.aragon.org/docs/aragonos-ref.html)

These need approving by the Aragon One design team prior to going live.

**Comment by sohkai** [comment]
One thing that's not _super_ great about mermaid is that I haven't been able to find ways to change a graph's layout, if the rendered one wasn't to my liking. Might not be a blocker though.

**Comment by lkngtn** [comment]
> One idea from @0x6431346e is to use Mermaid

I don't think mermaid will allow you to create charts like the ones linked. 

If its helpful I can also provide the original keynote for those animations, though keynote may not be the best tool for this long term.

**Comment by cjyabraham** [comment]
These diagrams should also be updated to account for naming changes of the Aragon components:
* Aragon Package Manager ==> aragonPM
* Aragon CLI ==> aragonCLI
* Kit ==> Template
* Aragon Core ==> Aragon client
* aragon.js ==> aragonAPI
* Aragon UI ==> aragonUI
* Aragon ID ==> aragonID
* Kits ==> Templates

**Comment by cjyabraham** [comment]
@sohkai should "aragon.js" be "aragonAPI" in [this image](https://hack.aragon.org/docs/assets/fwd.gif)?  Or do we need to say "the JS implementation of aragonAPI" ??

**Comment by sohkai** [comment]
Closing as this has gone stale and we've introduced many changes since this was started.
