### ISSUE TITLE
Fix naming of Aragon components in images

### ISSUE THREAD

**Issue by cjyabraham** [aragon/hack#63]
Aragon has changed the names of certain components recently:
* Aragon Package Manager ==> aragonPM
* Aragon CLI ==> aragonCLI
* Aragon Core ==> Aragon client
* aragon.js ==> aragonAPI
* Aragon UI ==> aragonUI
* Aragon ID ==> aragonID

Make the same changes for images and diagrams on hack.aragon.org.  These need fixing:
* [header image](https://hack.aragon.org/docs/aragonjs-ref.html)
* [main diagram](https://hack.aragon.org/docs/stack.html)
* [header image](https://hack.aragon.org/docs/cli-usage.html)
* [header image](https://hack.aragon.org/docs/apm.html)

**Comment by sohkai** [comment]
Adri made these originally and it'd probably be easiest for him to change them.

**Comment by cjyabraham** [comment]
Ok, cool.  I don't see him in the assignees list.  What's the best way to get it on his todo list?

**Comment by sohkai** [comment]
@cjyabraham I think he's mostly on our internal task board and not on Github; pinged him there!

**Comment by Smokyish** [comment]
Additional items to complete list of images that need to be changed related to this:

https://github.com/aragon/design/blob/master/logos/export/aragon-package-manager-horizontal.png
https://github.com/aragon/design/blob/master/logos/export/aragon-package-manager-vertical.png
https://github.com/aragon/design/blob/master/logos/export/aragoncli-horizontal.png
https://github.com/aragon/design/blob/master/logos/export/aragoncli-vertical.png
https://github.com/aragon/design/blob/master/logos/export/aragonjs-horizontal.png
https://github.com/aragon/design/blob/master/logos/export/aragonjs-vertical.png

**Comment by sohkai** [comment]
These images have been updated to use their new names.
