### ISSUE TITLE
Remove Metamask from docs

### ISSUE THREAD

**Issue by cjyabraham** [aragon/hack#70]
It’s Luis’ wish to remove Metamask as a must-have in the docs when Frame is ready for prime time.  Could we make the docs agnostic?

**Comment by sohkai** [comment]
We've mostly done this in the client through provider-agnostic language, e.g. "Ethereum provider".

We'll likely have some sort of micropage built later for explaining exactly what an "Ethereum provider" is, but for now we could include a page that lists a few of them.

However, I'm not 100% sure Frame would be ready for this as I don't think there's a way to provide development keys yet.

**Comment by cjyabraham** [comment]
I think if we go completely agnostic here we'll lose [important](https://hack.aragon.org/docs/cli-usage.html#using-metamask) [instructions](https://hack.aragon.org/docs/human-readable-txs.html) on how to use Metamask (or equivalent).  If we want to swap in Frame for Metamask as our recommended provider, I think we should wait on that until Frame is ready.

**Comment by 0xGabi** [comment]
Close in #99
