### ISSUE TITLE
Warn about initialization of global variables in app guide

### ISSUE THREAD

**Issue by sohkai** [aragon/hack#76]
See https://github.com/aragon/aragon-cli/issues/26.

**Comment by 0xGabi** [comment]
Not sure about the place where this new documentation will exist. I added it in the new Troubleshooting guides.

@sohkai I'm unsure if by "app guide" you meant your first aragon app tutorial?

**Comment by sohkai** [comment]
@0xGabi Actually we have a good page for it now, the "Developing with aragonOS" page: https://hack.aragon.org/docs/aragonos-building.

**Comment by 0xGabi** [comment]
Close in #99
