### ISSUE TITLE
Add windows-build-tools note for Windows users

### ISSUE THREAD

**Issue by sohkai** [aragon/hack#77]
They likely also need the [windows-build-tools](https://www.npmjs.com/package/windows-build-tools) package installed if they have problems installing the CLI or any other dependencies.

**Comment by kernelwhisperer** [comment]
We should warn them that running the shell as Administrator is required when installing the CLI.

```
EPERM: operation not permitted, symlink 'E:\repos\aragon\aragon-cli\node_modules\go-ipfs-dep\go-ipfs\ipfs.exe' -> 'E:\repos\aragon\aragon-cli\node_modules\go-ipfs\bin\ipfs.exe'
```

**Comment by sohkai** [comment]
This sounds like it could be an `nvm` problem to me (assuming the permissioning is based on the path and not just executing `.exe`s?), and most Windows users should use [`nvm-windows`](https://github.com/coreybutler/nvm-windows). I guess we could put it as a recommendation along with `windows-build-tools`?

@0xGabi could you try this at some point on Windows?

**Comment by 0xGabi** [comment]
Sure, I'll do it this week

**Comment by kernelwhisperer** [comment]
Oh... it might be on my part then, I installed `node` using `chocolatey`.
> First, ensure that you are using an administrative shell - you can also install as a non-admin, check out Non-Administrative Installation.

I will try to install `chocolatey` without admin rights and report back.

**Comment by 0xGabi** [comment]
I confirm that in my windows pc I didn't need to run in admin mode to install the CLI.

My computer specs are: 
- Windows 10
- `node v10.15.0`
- `npm 6.4.1`
- `git` and `windows-build-tools` installed

**Comment by kernelwhisperer** [comment]
> I confirm that in my windows pc I didn't need to run in admin mode to install the CLI.
> 
> My computer specs are:
> 
> * Windows 10
> * `node v10.15.0`
> * `npm 6.4.1`
> * `git` and `windows-build-tools` installed

Hmm, weird.
I managed to re-install everything with non-admin rights, except `go-ipfs`, until I allowed my user to create symlinks (which by default only Admins can).
https://superuser.com/a/105381

**Comment by 0xGabi** [comment]
I will check that, might have had `go-ipfs` already installed 🤔

**Comment by 0xGabi** [comment]
Close in #99
