### ISSUE TITLE
Improve aragonPM reference doc

### ISSUE THREAD

**Issue by 0xGabi** [aragon/hack#96]
Suggested changes for `apm-ref.md`:

- [ ] Include an introduction/definition for APMRegistry

- [ ] Better links

**Comment by sohkai** [comment]
We could also include some suggested use cases (e.g. our metadata database)!

**Comment by sohkai** [comment]
Fixed with https://github.com/aragon/hack/pull/143, added https://github.com/aragon/hack/issues/155 for suggested use cases.
